services:
  - type: web
    name: peak-automation-ui
    env: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: streamlit run ui.py --server.address=0.0.0.0 --server.port=$PORT
    autoDeploy: true